### ISSUE TITLE
Event payload only contains string with the name of the event, not an object

### ISSUE THREAD

**Issue by ledezman** [datacamp/datacamp-light#103]
I need to integrate datacamp-light results with my application. I followed the guide here https://cdn.datacamp.com/dcl-react-prod/index.html#tutorial-customizing-integrating

I am able to register the events, and they are indeed triggered by the start/submit actions. However the payload only contains a string, not the payload object specified in the guide. 

Here is the sample HTML:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Chapter 5 Exercise 13</title>
        <script async src="https://cdn.datacamp.com/dcl-react.js.gz"></script>
        <script>
            window.onload = function () {
                console.log(DCL.instances);
                DCL.instances["test1"].on("start", function(payload) {
                    alert("START");
                    console.log("PAYLOAD START");
                    console.log(payload);
                    console.log("PAYLOAD END");
                });

                DCL.instances["test1"].on("submit", function(payload) {
                    alert("Submit");
                    console.log("PAYLOAD START");
                    console.log(payload);
                    console.log("PAYLOAD END");
                });

                DCL.instances["test1"].on("feedback", function(payload) {
                    alert("Feedback");
                    console.log("PAYLOAD START");
                    console.log(payload);
                    console.log("PAYLOAD END");
                });
            };
        </script>
    </head>
    <body>
        <div data-datacamp-exercise data-lang="r" data-show-run-button = TRUE id='test1'>
            <code data-type="pre-exercise-code">
                 require(mosaic)
                 require(ggformula)
                 require(supernova)
 Empty.model <- lm(Thumb ~ NULL, data=Fingers)
                Fingers$Prediction <- predict(Empty.model)
                 Fingers$Residual <- resid(Empty.model)
            </code>
            <code data-type="sample-code">
            # make histograms for Thumb, Prediction, and Residual
            </code>
            <code data-type="solution">
            # make histograms for Thumb, Prediction, and Residual
                gf_histogram(~Thumb, data = Fingers)
                gf_histogram(~Prediction, data = Fingers)
                gf_histogram(~Residual, data = Fingers)
            </code>
            <code data-type="sct">
                ex() %>% check_function("gf_histogram", index = 1) %>%  check_arg("object") %>% check_equal() 
                ex() %>% check_function("gf_histogram", index = 1) %>% check_arg("data") %>% check_equal()
                ex() %>% check_function("gf_histogram", index = 2) %>% check_arg("object") %>% check_equal()
                ex() %>% check_function("gf_histogram", index = 2) %>% check_arg("data") %>% check_equal()
                ex() %>% check_function("gf_histogram", index = 3) %>% check_arg("object") %>% check_equal()
                ex() %>% check_function("gf_histogram", index = 3) %>% check_arg("data") %>% check_equal() 
                ex() %>% check_error()
                
            </code>
            <div data-type="hint">Don't forget to make all three histograms!</div>
        </div>
    </body>
</html>
```

Alerts are shown,  console output:

```
Object
datacamp.html:12 PAYLOAD START
datacamp.html:13 start
datacamp.html:14 PAYLOAD END
dcl-react.js.gz:9 registering autocomplete
datacamp.html:19 PAYLOAD START
datacamp.html:20 submit
datacamp.html:21 PAYLOAD END
datacamp.html:26 PAYLOAD START
datacamp.html:27 feedback
datacamp.html:28 PAYLOAD END
```

**Comment by iamarcel** [comment]
Good catch! I'd implemented the listeners with two arguments `(type: string, payload: any)` instead of what's described. I've changed the code to reflect the documentation on the development branch, which will soon make it to the stable version.

If you want to use this immediately, you can change your function signatures and use the payload in the second argument (but note that that'll change as the first argument will be dropped).

**Comment by ledezman** [comment]
Great, thank you.  I'll test changing the method signature for now. My code is not in production yet, but by the time it does datacamp-light stable will probably have the update.

**Comment by iamarcel** [comment]
It seems like the build isn't triggering as it should, so the developer version script is not up to date right now. @rv2e do you know why that could be?

**Comment by rv2e** [comment]
@iamarcel I'll try to fix the deployment workflow today. In the meantime, could you create PRs for the fixes you've done please so it's easier to follow 😄

**Comment by iamarcel** [comment]
Okay, sorry for the confusion!


On Fri, Aug 24, 2018, at 09:32, rv2e wrote:
> @iamarcel[1] I'll try to fix the deployment workflow today. In the
> meantime, could you create PRs for the fixes you've done please so
> it's easier to follow 😄> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/iamarcel
  2. https://github.com/datacamp/datacamp-light/issues/103#issuecomment-415677273

**Comment by rv2e** [comment]
@iamarcel I've fixed the CircleCI deployment, you can test it now easily. Feel free to create a PR ;)

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-71

**Comment by WeatherAnchor** [comment]
Hey, did anyone actually fix this issue?

**Comment by nunorafaelrocha** [comment]
Hi @WeatherAnchor 

Yes, this was fixed, but it's only available on v3, which is currently under the beta tag

Link here: https://github.com/datacamp/datacamp-light/tree/v3.0.0-beta.1
