### ISSUE TITLE
RStudio and Bookdown: LazyLoading of exercises not working

### ISSUE THREAD

**Issue by martinschmelzer** [datacamp/datacamp-light#106]
When creating a bookdown document using your example exercises, the first exercise loads normally.
The others do not load when scrolling them into the viewport. It is like the "inViewport" event is not triggered.
When generating basic RMarkdown document with several exercises it works as expected.

**Comment by rv2e** [comment]
We could add an option to disable the lazy loading functionality. This should solve your problem.

**Comment by cstigler** [comment]
We're also having this issue, loading DCL exercises inside of Learnosity questions. My guess is that the iFrame that Learnosity puts the exercise in is some/all of the issue.

The lazy load also appears not to work if re-rendering into an area that is already visible on the page: it stays stuck on the placeholder until I scroll again. Ideally DCL would detect that it's already rendered in a visible area and load itself immediately.

An option to turn off lazy loading would be greatly appreciated. I'd try to submit a PR myself but am unfortunately having issues building the codebase...

**Comment by cstigler** [comment]
Submitted a PR to add an option to disable lazy-loading, which should fix these issues: https://github.com/datacamp/datacamp-light/pull/136
