### ISSUE TITLE
No license on version 2.0

### ISSUE THREAD

**Issue by jimstigler** [datacamp/datacamp-light#107]
I notice there is no license file for the new version of DataCamp Light. Is this an accidental omission, or has the license changed? Thanks for clarifying.

**Comment by rv2e** [comment]
It's an accidental omission, you' will put it back soon.

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-45
