### ISSUE TITLE
Placement of Run and Submit buttons

### ISSUE THREAD

**Issue by jimstigler** [datacamp/datacamp-light#109]
It would be a better UI to have the Submit button to the *right* of the Run button. The expected workflow for students would be for them to try some things using the Run button, then when they are ready, push Submit. People tend to think left to right, and would be more likely to remember they need to Submit if the button is to the far right. also: I would suggest that the Submit button be a different color (maybe blue) to mark that this is the action that is being graded (we are using the callback).

**Comment by ncarchedi** [comment]
Thanks for the suggestion @jimstigler. This is how we do it in the traditional datacamp interface, so I'm not sure why we couldn't have it the same here.

Example:

<img width="1440" alt="screenshot 2018-11-06 11 39 15" src="https://user-images.githubusercontent.com/4229089/48079082-9da70180-e1b8-11e8-9b50-9c423d075844.png">

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-68
