### ISSUE TITLE
Wordpress plugin

### ISSUE THREAD

**Issue by aiitfuture1** [datacamp/datacamp-light#111]
Could you please update the DataCamp-light plugin for Wordpress because the new version better than the old version.

Also, I have a question:
Is there any problem if I use the DataCamp-light plugin on my online courses?

Thank you in advance.

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-58

**Comment by aiitfuture1** [comment]
Thank you so much but you didn't answer my question
Is there any problem if I use the DataCamp-light plugin on my online courses?

**Comment by ncarchedi** [comment]
@aiitfuture1 by "problem", do you mean legal or technical? We just added a [license](https://github.com/datacamp/datacamp-light/blob/master/LICENSE.md) to make the legal side more clear.

**Comment by aiitfuture1** [comment]
Thank you ncarchedi
I mean legal 
To be honest I do not quite understand the difference between GNU and MIT license so that I'm asking you:
I sell online courses, is there any legal problem if I use the DataCamp-light on my courses?
