### ISSUE TITLE
babel-polyfill breaks if it's already used on the page

### ISSUE THREAD

**Issue by cstigler** [datacamp/datacamp-light#112]
Hi all! I noticed that DataCamp Light was breaking when installed on one particular page. After some investigation, it looks like the reason is that my page is already using `babel-polyfill`, and when DataCamp Light attempts to load `babel-polyfill` again, it throws the error `only one instance of babel-polyfill is allowed`.

I looked at the [babel-polyfill docs](https://babeljs.io/docs/en/babel-polyfill/), and they say that it should be used only in applications, **not** in libraries/tools (presumably to avoid this issue).

**Would it be possible to remove `babel-polyfill` so DataCamp Light will be compatible with pages that already use that library?**

Based on [other open-source libraries](https://github.com/lebab/lebab/issues/249) that have had similar issues, it looks like a reasonable path forward would be to use the `transform-runtime` plugin instead and avoid the polyfill altogether. There's also an [idempotent-babel-polyfill](https://github.com/codejamninja/idempotent-babel-polyfill/) library which is (obviously) idempotent, but I'm not clear as to whether both libraries would need to use the idempotent version to get that behavior, which would make it less than ideal.

**Comment by ncarchedi** [comment]
@cstigler thanks for the suggestion - we can definitely have a look at this.

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-69

**Comment by jimstigler** [comment]
Hi, is there any update on this issue? It is causing us some problems with our application... Thanks.

**Comment by nunorafaelrocha** [comment]
Reopening for visibility. We're working on this issue at the moment - this means that it should be done until next Friday, Feb 1.

**Comment by jordanwade** [comment]
Fixed in v2.1.0
