### ISSUE TITLE
Annoying behavior when working with DCL in an iFrame

### ISSUE THREAD

**Issue by jimstigler** [datacamp/datacamp-light#113]
In the new DCL, there is an annoying behavior that I wish could be fixed. I embed DCL in an iFrame, using code like this:
```
<p><iframe style="border: 0px #ffffff none;" src="https://uclatall.github.io/czi-stats-course/data-camp/sandbox-350" width="100%" height="350"></iframe></p><br>
```
The problem is, if I put this code on a page and then try to add other text to the page, my cursor keeps losing focus: I can only type one letter on the page before the cursor goes away. The problem seems to be that the DCL script keeps hitting the server, or something. The old DCL didn't have this problem. And, it's an annoying problem. Thanks for considering.

**Comment by ncarchedi** [comment]
Thanks @jimstigler - we'll have a look at this.

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-69

**Comment by ncarchedi** [comment]
@jimstigler for context, we currently use a shared package library for all datacamp light instances, which means adding/updating a package comes at the risk of breaking existing content. This obviously doesn't scale. 

Over the next few weeks, we'll move to a system closer to the one we use for standard datacamp courses, which will allow versioning of dependencies.
