### ISSUE TITLE
html syntax is showing up in datacamp lite on the community 

### ISSUE THREAD

**Issue by RyanSDC** [datacamp/datacamp-light#116]
cc @dwaynemartin 
The datacamp lite exercises have '`<strong><strong>'` in them. 

https://www.datacamp.com/community/tutorials/regular-expressions-clean-strings

![image](https://user-images.githubusercontent.com/39916176/46370743-7490cf80-c654-11e8-96c4-5855711fb062.png)

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-42

**Comment by KevinVanthuyne** [comment]
This issue seems to have been fixed. Can this be verified and closed?
