### ISSUE TITLE
packages not updated

### ISSUE THREAD

**Issue by jimstigler** [datacamp/datacamp-light#118]
Hi, I would appreciate it if you could update the following packages from CRAN:

- mosaic
- mosaicData
- mosaicCore
- Matrix
- ggformula
- ggplot2
- lattice
- dplyr

Thanks, 
Jim

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-59
