### ISSUE TITLE
Request to Install Packages

### ISSUE THREAD

**Issue by ewfreesRes** [datacamp/datacamp-light#122]
Hello.

We are enjoying using the Datacamp Lite tool and have it working at one site: https://ewfreesres.github.io/RegressModel/.

We would like to get this going for another two courses but, to make this happen, need the following packages installed:

- actuar
- alabama
- epitools
- GB2
- pander
- VGAM
- copula
- psych
- car

Questions, of course, most welcome to Jed Frees, jfrees@bus.wisc.edu, or Jake Thornton, thornton4@wisc.edu

Thanks in advance, Jed and Jake.

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint.

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-47
