### ISSUE TITLE
CORS Error in Production

### ISSUE THREAD

**Issue by svarlamov** [datacamp/datacamp-light#129]
IDE not loading and receiving CORS errors when used from a non-DC website. Failing example [here](https://exlskills.com/learn-en/courses/learn-python-essentials-for-data-science-intro_to_python/basic-python-BXEmgvphLBAW/variables-iOwUkcmfgmpU/floats-qgKSzvLBdyTH)

**Comment by svarlamov** [comment]
Also happens on DC sites now too: https://cdn.datacamp.com/dcl-react/standalone-example.html

**Comment by rv2e** [comment]
Thanks for reporting the issue, an update of the app has been deployed which fixes your problem automatically. I've just tested the update on your website and it works now ([screenshot](https://www.dropbox.com/s/jow20dfe3ehkcdf/Screenshot%202018-11-27%2010.35.56.png?dl=0)).
