### ISSUE TITLE
Tutorial vignette renders strangely

### ISSUE THREAD

**Issue by filipsch** [datacamp/datacamp-light#16]
If you go to https://www.github.com/datacamp/tutorial, pull the package, open it up in RStudio, and then call

```
devtools::build_vignettes()
```

The vignette will be built in the `inst/doc` folder. If you open up the HTML that has been built, you get the following:

[Script selected](https://www.dropbox.com/s/bvqdvk00rbui8op/Screenshot%202016-08-01%2009.48.31.png?dl=0)
[Console selected](https://www.dropbox.com/s/cqawdou6b7m39t5/Screenshot%202016-08-01%2009.48.58.png?dl=0)

Which is strange. It can be something in `tutorial` as well, but with earlier versions of datacamp light it looked fine...

**Comment by EvertEt** [comment]
@filipsch Could you check if the issue has been resolved?

**Comment by filipsch** [comment]
Perfect! Thanks bro
