### ISSUE TITLE
R Console Label Bug

### ISSUE THREAD

**Issue by iankloo** [datacamp/datacamp-light#17]
The R Console label has moved into a position where it is blocking the executed code (see below).

![issue](https://cloud.githubusercontent.com/assets/13052891/17440090/14a12994-5af9-11e6-84ee-20238b4314d3.PNG)

Love the library!  Very helpful for making custom tutorials without having to send people to another website.

**Comment by EvertEt** [comment]
Could you link me the page where this is happening? Is it also happening on the [example page](https://cdn.datacamp.com/dcl/standalone-example.html)? Browser & OS? 
Thank you!

**Comment by iankloo** [comment]
Hm, no issue with the example page.  Issue is happening on documents created through R Markdown using the tutorial package.  I am working on finalizing a project that I plan to post in the next week or so - can link to that then.

Thanks!

**Comment by EvertEt** [comment]
Great! You can always send me the html so I can check which conflicting CSS messes with DCL. Otherwise I will check once your project is released.
Thanks for reporting!

**Comment by filipsch** [comment]
@iankloo this is probably the RMarkdown CSS interfering with the one of DataCamp Light...
