### ISSUE TITLE
Hello World example don't working

### ISSUE THREAD

**Issue by maxreeb** [datacamp/datacamp-light#183]
Hello,

I have discovered recently datacamp light and trying to get a first example to run.
But unfortunatelly I wasn't successful.

Please, can you tell me what is wrong with this example or missing?
My browser loads only the comment line. There is nothing else.

Thanks in advance!

Kind regards,
Max 

**Code**
![hello_world_code](https://user-images.githubusercontent.com/75696376/101533005-9c4af300-3995-11eb-932e-ad35d52b56ae.png)

**Output**
![hello_world_output](https://user-images.githubusercontent.com/75696376/101533206-d6b49000-3995-11eb-892d-8029b38f8358.png)

**Comment by flavves** [comment]
ı cant open your link please sen again
*Batuhan ÖKMEN*

*IEE ISUBÜ Öğrenci Kolu | Sponsorluk Ve Kurumsal İlişkiler Komitesi Başkan
yard.*
*Mekatronik Mühendisliği*
*Isparta/TÜRKİYE*
*GSM*: +90 534 021 11 89
*WEB batuhanokmen.com <https://batuhanokmen.com/>*


maxreeb <notifications@github.com>, 8 Ara 2020 Sal, 22:36 tarihinde şunu
yazdı:

**Comment by maxreeb** [comment]
Hi flavves,

I have uploaded the example on a test server.
http://www.web177.s138.goserver.host/datacamp_light_hello_world.html

I got the error message: Session broken

**Comment by maxreeb** [comment]
I just found out that the issue was related to google chome or my chrome installation. It works with firefox and edge for me. thanks again!
