### ISSUE TITLE
Urgent: All DataCamp sessions broken

### ISSUE THREAD

**Issue by adamblake** [datacamp/datacamp-light#187]
All DataCamp sessions are broken using setups that worked as of yesterday. Here are the errors, some screenshots from Chrome and Firefox, and the source code of the example:

### Error in Chrome Dev Console:
> dcl-react.js.gz:14 POST https://multiplexer-prod.datacamp.com/new?language=r&force_new=true net::ERR_CERT_AUTHORITY_INVALID

![image](https://user-images.githubusercontent.com/6201730/110519363-13da0c80-80c2-11eb-820b-d65e4c9ee4b1.png)

### Error in Firefox Dev Console:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://multiplexer-prod.datacamp.com/new?language=r&force_new=true. (Reason: CORS request did not succeed).

![image](https://user-images.githubusercontent.com/6201730/110519655-703d2c00-80c2-11eb-9d2e-9d2eeee270a5.png)

### Source Code

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Chapter 2 Exercise 1</title>
    <script type="text/javascript" src="https://cdn.datacamp.com/dcl-react.js.gz"></script>
</head>
<body>
    <div data-datacamp-exercise data-lang="r">
        <code data-type="pre-exercise-code"></code>
        <code data-type="sample-code">
            # Here's how to combine nine 2s into a vector
            # You could also use rep(2, times = 9)
            myvector1 <- c(2, 2, 2, 2, 2, 2, 2, 2, 2)

            # Create a vector called myvector2 with the numbers
            # 2, 1, 3, 3, 2, 3, 1, 2, 1
            myvector2 <- c()
        </code>
        <code data-type="solution">
            myvector2 <- c(2, 1, 3, 3, 2, 3, 1, 2, 1)
        </code>
        <code data-type="sct">
            ex() %>% check_object("myvector2") %>% check_equal()
        </code>
        <div data-type="hint">Use the c() function to combine items into a single vector.</div>
    </div>
</body>
</html>
```

**Comment by LovisaFJSundin** [comment]
Same for me. Have they shut down their servers?

**Comment by jimstigler** [comment]
Anyone over at DataCamp listening? All my students are down, can't do their homework!

**Comment by KarenGivvin** [comment]
Please help!

**Comment by jdmunro** [comment]
Hey, thank you for the detailed issue report. Apologies for the inconvenience to you/interruption to your students. We had an SSL configuration issue which has now been resolved: you should find the service is functioning normally now. Thanks for your patience while we resolved the issue!

**Comment by adamblake** [comment]
Thank you for the response, but the issue does not appear to be fully resolved. All of our sessions are still broken, but the error has changed to 

> Failed to load resource: the server responded with a status of 403 () https://multiplexer-prod.datacamp.com/new?language=r&force_new=true

I hope this helps

**Comment by adamblake** [comment]
I don't know if you get notifications on closed issues, so I'm tagging you just in case @jdmunro

**Comment by jdmunro** [comment]
@adamblake Currently looking into this, thanks again. Will report back when we have an update.

**Comment by jhwang1** [comment]
Likewise. All day yesterday and all this morning. I am receiving a ton of emails from students!

**Comment by jdmunro** [comment]
We have experienced some platform instability today which has unfortunately impacted DataCamp Light. Currently, the service is back up and functioning normally and we're continuing to monitor the situation. Apologies again for the interruption to your student's learning experience - please let us know here if you experience a further interruption to the service.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
The same thing is happening again!!

**Comment by SANTHOSH-MAMIDISETTI** [comment]
![image](https://github.com/datacamp/datacamp-light/assets/92091342/2f22b2e8-822d-4fbc-a780-2b11fbbfa204)
![image](https://github.com/datacamp/datacamp-light/assets/92091342/38c03a1d-7733-4f64-ab66-84066de6cbe2)
