### ISSUE TITLE
Urgent: DataCamp sessions broken 

### ISSUE THREAD

**Issue by jiyunson** [datacamp/datacamp-light#188]
They are all down in our use cases and I checked DataCamp Light's own demo page and those seem to be down as well: https://cdn.datacamp.com/dcl-react/standalone-example.html

It feels like a deja vu...  https://github.com/datacamp/datacamp-light/issues/187

**Comment by EH-code** [comment]
Same here. Data Camp has not been working this morning. I keep receiving the "session broken" message.

**Comment by lvanacken** [comment]
Thanks for reporting this.
We have experienced some platform instability today which has unfortunately impacted DataCamp Light. Currently, the service is back up and functioning normally and we're continuing to monitor the situation. Apologies again for the interruption to your student's learning experience - please let us know here if you experience a further interruption to the service.

If in doubt you can always take a look at: https://status.datacamp.com/
It contains the latest updates regarding the platform. DataCamp Light relates to DataCamp Courses on that page.

**Comment by nunorafaelrocha** [comment]
Hello @jiyunson and @EH-code 

The services are stable at the moment, so I'll close this ticket for now. Once again, apologies for any inconvenience this may have caused.

In case of session problems, please check https://status.datacamp.com/ to get the latest updates regarding the status of the platform.

**Comment by jiyunson** [comment]
Thank you! We appreciate the quick response.
