### ISSUE TITLE
Urgent Data Camp Sessions Broken

### ISSUE THREAD

**Issue by EH-code** [datacamp/datacamp-light#189]
Hi  Thanks for fixing yesterday's issue quickly. Unfortunately it has returned. I'm receiving the 'session broken' message again.

**Comment by nunorafaelrocha** [comment]
Hi @EH-code 

Thanks for reporting this issue.

We suffer some instabilities during the afternoon. At this moment, all systems are operational, but we're still monitoring the situation closely.

Please, follow up updates using our [status page](https://status.datacamp.com/).

Thanks!
