### ISSUE TITLE
Make the powered by DataCamp a bit smaller

### ISSUE THREAD

**Issue by ddmkr** [datacamp/datacamp-light#19]
It's a bit invasive at the moment.

**Comment by EvertEt** [comment]
Any size suggestions?

**Comment by ludov04** [comment]
@EvertEt On Rdoc I set the `font-size` to `15px`, looks ok:
![screen shot 2016-08-22 at 17 55 55](https://cloud.githubusercontent.com/assets/1741726/17861536/bccec4f0-6891-11e6-9a8b-1df916c22377.png)

**Comment by EvertEt** [comment]
@ludov04 Looks good.

**Comment by iamarcel** [comment]
In the new [beta version](https://github.com/datacamp/datacamp-light/tree/beta), we've made the logo a lot smaller! To try it out, just change the script tag to this:

```js
<script type="text/javascript" src="//cdn.datacamp.com/dcl-react.js.gz"></script>
```

![screenshot from 2018-05-30 16-24-12](https://user-images.githubusercontent.com/1212234/40726491-26f193b2-6426-11e8-9158-42b1778b57eb.png)
