### ISSUE TITLE
R package request: supernova upgrade to 2.4.0 from 2.0.0

### ISSUE THREAD

**Issue by adamblake** [datacamp/datacamp-light#190]
Hello, we use DataCamp Light to teach statistics and we wrote the `supernova` package to teach ANOVA. Can you please upgrade the package to the current version? The upgrade will only add features and fix bugs, and there are no known reverse dependencies with the package.

Ideally we would like this package updated as often as possible, and the `HEAD` of our repository will always be stable. So you could use 

```r
remotes::install_github("UCLATALL/supernova")
```

Alternatively, we update it on CRAN frequently

```r
install.package("supernova")
```

**Comment by jdmunro** [comment]
Hey @adamblake - we're currently taking a look into what this would involve.

I notice that the `supernova` package requires an R version of `3.5.0` or greater: https://github.com/UCLATALL/supernova/blob/main/DESCRIPTION#L32

The runtime for DataCamp Light is currently based on an older R version (3.4.0). Whilst we would ultimately like to keep this up-to-date, it could involve a lot of work to bring this forward as we have to consider the compatibility with other packages/consumers of DCL. Does the `supernova` package depend on anything specific in R 3.5.0, or could it in theory have the constraint relaxed to work with 3.4.0?

**Comment by adamblake** [comment]
I will look into that dependency today and get it compatible with R 3.4

**Comment by adamblake** [comment]
@jdmunro `supernova` is now updated to 2.4.1 on CRAN to be backwards compatible with R 3.4.0

Thanks for your patience while I worked out the bugs on that!

**Comment by jdmunro** [comment]
@adamblake Thanks for that! I'll try and get that updated at our end this week - I'll keep you posted.

**Comment by adamblake** [comment]
Hi @jdmunro --- any update on this? Thanks for your help!

**Comment by jdmunro** [comment]
Hey @adamblake - apologies for my slow response! We've taken an in-depth look at this and discovered further problems that are going to require additional time and bandwidth for us to resolve. Unfortunately, there are still other issues related to the age of the runtime environment (not directly related to `supernova`) and it's clear an overhaul is required. As a result, we will be postponing the upgrade for a few months. Thank you for your patience and the work you did on `supernova` to relax the runtime constraints.
