### ISSUE TITLE
Allow external callbacks

### ISSUE THREAD

**Issue by kruny1001** [datacamp/datacamp-light#2]
I am trying to apply datacamp-light into our website. It works great. Is there any way to get a callback after success problem?

**Comment by KaiserW** [comment]
I'm afraid not, since datacamp-light is an IFrame tool.

**Comment by EvertEt** [comment]
I will look into it to see if it's possible. Have you got any structure in mind of how this would work?

**Comment by dmunguia** [comment]
I vote +1 for this issue, It would be great to have something like this to be able to integrate DCL results into other tools.

**Comment by iamarcel** [comment]
We're keeping issues in the issue tracker for bugs only, now, so I'll close this and [move it to the roadmap](https://github.com/datacamp/datacamp-light/projects/1#card-10364266). Looks like a lot of people would like this feature too, so expect it soon :smile:

**Comment by iamarcel** [comment]
@kruny1001 @dmunguia 

This feature is now available! You can add a callback when a student starts DataCamp Light, when they submit a solution and when feedback for the exercise is returned (which includes whether the solution was correct).

[Check out the details on the documentation page.](https://cdn.datacamp.com/dcl-react-prod/index.html#tutorial-customizing-integrating)
