### ISSUE TITLE
Expose a function allowing to rerender exercices added after DOMContentLoaded

### ISSUE THREAD

**Issue by ludov04** [datacamp/datacamp-light#21]
There is currently no way to rerender exercices that has been added in the DOM after the DOMContentLoaded event.

We could expose an function that would initialize newly added exercices

**Comment by EvertEt** [comment]
I was indeed planning on exporting `initDataCampExercises` into `window`. Maybe also replace `dclLoaded` with a check of this exported function.
(It was planned for usage in the DCL builder.)

**Comment by ludov04** [comment]
I tried to worked around it by refiring the DOMContentLoaded event, this run `initDataCampExercises` but then the script tag is readded, and the browser try to reload angular and stuffs.
I think an exposed version of `initDataCampExercises ` but without the 
```
checkPoweredBy();
loadScriptAsync(DCL_URL + '{{scriptLink}}');
```
would work

**Comment by EvertEt** [comment]
Indeed.
A PR would be welcome, or I can do this when I have more time if it's not urgent.
