### ISSUE TITLE
regarding libraries ?

### ISSUE THREAD

**Issue by suriyaJaay** [datacamp/datacamp-light#26]
Could anyone tell me how many std libraries that datacamp-light has support so far?

**Comment by filipsch** [comment]
@suriyaJaay currently, practically all R packages that are on CRAN and a vast amount of python packages are available. Some R packages can be outdated or missing.
If you want to use a particular package that's not available or not up to date, let us know and we can install it (DataCamp Light users cannot install packages themselves.)

**Comment by suriyaJaay** [comment]
@filipsch thanks for your lighting response . well actually i just want implement it in my small blog that would help students to learn practically those who cannot afford to take courses from outside. so that want use datacamp, is it possible to load datacamp light with all packages ?

**Comment by filipsch** [comment]
@suriyaJaay If you insert datacamp light in a blog of yours, automatically all packages that we have installed on our R servers and Python servers are available for you to use. Does this answer your question?
