### ISSUE TITLE
regarding libraries ?

### ISSUE THREAD

**Issue by suriyaJaay** [datacamp/datacamp-light#27]
@filipsch thanks for your lighting response . well actually i just want implement it in my small blog that would help students to learn practically those who cannot afford to take courses from outside. so that want use datacamp, is it possible to load datacamp light with all packages ? 

i would like to use  all available libraries/packages in data camplight if its not possible, kindly suggest some other way to use all packages and libraries in datacamp

**Comment by filipsch** [comment]
See #26
