### ISSUE TITLE
Installing external packages

### ISSUE THREAD

**Issue by mplex** [datacamp/datacamp-light#29]
Hi, This is a promising work for e-learning, and congrats so far...

I was wondering whether is possible to install R packages either from CRAN or from Github?

**Comment by filipsch** [comment]
@mplex nearly all packages from CRAN or installed (but they're not necessarily the latest version). We do installs and updates on a by-request basis. If you have any requests, feel free to let us know.

**Comment by mplex** [comment]
Thanks @filipsch for the reply.
I was trying to load a package in the [demo R and Python example](https://cdn.datacamp.com/dcl/standalone-example.html). So I guess loading is possible in the widget.
