### ISSUE TITLE
Multiple choice question

### ISSUE THREAD

**Issue by nadimmajed** [datacamp/datacamp-light#30]
Hello,
How can I create a multiple choice question with datacamp-light, I have tried this code but there was an error : 
DataCamp encountered the following error:
DC_CODE not set.

`     <script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script>
      <div data-datacamp-exercise data-lang="python">
        
        <code data-type="pre-exercise-code">
          # pec
        </code>
        <code data-type="instructions">
          - `"I can add integers, like "  + str(5) + " to strings."`
          - `"I said " + ("Hey " * 2) + "Hey!"`
          - `"The correct answer to this multiple choice exercise is answer number " + 2`
          - `True + False`

        </code>
        
        <code data-type="sct">
          msg1 = msg2 = msg4 = "Incorrect, this command runs perfectly fine."
          msg3 = "Correct! Because you're not converting `2` to a string with [`str()`](https://docs.python.org/3/library/functions.html#func-str), this will give an error."
          test_mc(3, [msg1, msg2, msg3, msg4])
        </code>
        <div data-type="hint">Use the assignment operator .</div>
      </div>
    </div>`

Thankyou in advance.

**Comment by filipsch** [comment]
Hi @nadimmajed; unfortunately, multiple choice questions are not supported on DataCamp light... DCL only features a minimal version of the standard interactive exercise on DataCamp.

**Comment by nadimmajed** [comment]
Thankyou for your answer.
