### ISSUE TITLE
Install corrplot Package 

### ISSUE THREAD

**Issue by Kacawi** [datacamp/datacamp-light#33]
Could you install corrplot (https://www.rdocumentation.org/packages/corrplot/versions/0.2-0)? Thanks!

**Comment by filipsch** [comment]
@Kacawi, it's being installed; I'll let you know when it's up!

**Comment by filipsch** [comment]
@Kacawi it's available on datacamp light now if you have a new session. You can see it in the list of installed packages [here](http://documents.datacamp.com/default_r_packages.txt). Cheers!
