### ISSUE TITLE
Make sure DataCamp Light CSS can't be overridden

### ISSUE THREAD

**Issue by filipsch** [datacamp/datacamp-light#36]
If you're using DataCamp Light in certain themes, it's possible that the theme's CSS interfers with the CSS that DataCamp Light uses to render the iframe.

**Comment by mcroyle** [comment]
Is this something that's being looked at? I'm seeing this issue and I can't quite pin down which theme style is mucking up the Datacamp exercise area.

**Comment by filipsch** [comment]
@mcroyle we're actively working on a rework of DataCamp Light and will tackle this issue along with it. Thanks for flagging this; good to know it is still relevant.
