### ISSUE TITLE
Add Package Bioconductor 

### ISSUE THREAD

**Issue by Kacawi** [datacamp/datacamp-light#37]
Would it be possible to add the [bioconductor package](http://bioconductor.org)? Thanks!

**Comment by filipsch** [comment]
@Kacawi, is `bioconductor` itself a package? I think it's a group of packages from bioinformatics. Which packages specifically do you need?

**Comment by MahShaaban** [comment]
Hey @filipsch, @Kacawi is asking about `Bioconductor` to my request. You are right, `Bioconductor` is a group of packages. As explained in the [link](http://bioconductor.org/install/), installation are triggered by calling `biocLite`
```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite()
```
This is a script that _installs or updates Bioconductor and CRAN packages in a Bioconductor release_. This is done by installing `Biobase` _which is Functions that are needed by many other packages or which replace R functions_ and its dependencies.

**Comment by filipsch** [comment]
@MahShaaban @Kacawi the basic bioconductor packages should be in there. You can check the list of all available packages here: 
http://documents.datacamp.com/default_r_packages.txt

**Comment by MahShaaban** [comment]
Great. Thanks a lot.
