### ISSUE TITLE
Add Radarchart Packages

### ISSUE THREAD

**Issue by Kacawi** [datacamp/datacamp-light#38]
Would it be possible to install the following packages:
- [`fmsb`](https://www.rdocumentation.org/packages/fmsb/versions/0.5.2)
- [`radarchart`](https://www.rdocumentation.org/packages/radarchart/versions/0.3.1)

Thanks!

**Comment by filipsch** [comment]
@Kacawi it's building; will let you know once it's actually up and activated!

**Comment by filipsch** [comment]
@Kacawi should be up and running!
