### ISSUE TITLE
DataCamp Light Python Plots Don't Show

### ISSUE THREAD

**Issue by filipsch** [datacamp/datacamp-light#40]
@Kacawi commented on [Wed Apr 19 2017](https://github.com/datacamp/pm-learn/issues/26)

For R, the plots are shown in a separate "Plots" tab in the DataCamp Light chunks:
![screenshot 2017-04-19 10 06 31](https://cloud.githubusercontent.com/assets/8349123/25169782/94b5d602-24e8-11e7-94dd-3753053cd197.png)

For Python, the plots don't show in the separate "Plots" tab. There's only a question mark icon:
![screenshot 2017-04-19 10 10 24](https://cloud.githubusercontent.com/assets/8349123/25169807/afc4f0c2-24e8-11e7-838f-8a98818864db.png)

---

@filipsch commented on [Thu Apr 27 2017](https://github.com/datacamp/pm-learn/issues/26#issuecomment-297747368)

This should be rather easy to fix, we'll take it up asap.

**Comment by EvertEt** [comment]
Can it be that the python plot output is not hex anymore?

**Comment by filipsch** [comment]
@EvertEt exactly, it's SVG now... We know where the issue is, actually, just need time to fix it. This is the link to the relevant commit in Angular version of campus app: https://github.com/datacamp/campus-app/commit/fa9f74033badf89acb709d5cd56addcd04263288 (gave you temporary access to the repo again, if you want to look into it).

**Comment by filipsch** [comment]
Fixed! @Kacawi @machow
