### ISSUE TITLE
Add odbc Package

### ISSUE THREAD

**Issue by jbarillas** [datacamp/datacamp-light#43]
Would it be possible to add the odbc package?

Thank you very much!

**Comment by filipsch** [comment]
@jbarillas you are talking about the odbc R package right? What database do you want to connect to? I think the `odbc` package on its own won't suffice.

**Comment by jbarillas** [comment]
@filipsch  You are correct and I'm trying to connect to an SQL Server database so the current `DBI` package does not have a backend like `src_mysql()`. Therefore I'd need to use both the `DBI` and `odbc` packages like so:

```
con <- DBI::dbConnect(odbc::odbc(),
                      driver = "SQL Server",
                      server = <serverURL>,
                      database = <databasename>,
                      uid = <username>,
                      pwd = <passwd>)
```

**Comment by filipsch** [comment]
@jbarillas I can also install DBI and RMySQL, would that be better?

**Comment by jbarillas** [comment]
@filipsch I was looking through the [default_r_packages.txt](http://documents.datacamp.com/default_r_packages.txt) file, and I do see that `DBI` and `RMySQL` are already there. Unfortunately, my problem requires the ability to connect to an SQL Server so my options would be to use `odbc` or [RSQLServer](https://github.com/imanuelcostigan/RSQLServer) (which is not currently on CRAN).

**Comment by filipsch** [comment]
@jbarillas Can you let me know exactly which R package and which drivers you would need? R and bash commands to do the installs would also be very helpful! (the executor runs on Ubuntu 16.04)

**Comment by jbarillas** [comment]
@filipsch It'd be [version 1.0.1](https://www.rdocumentation.org/packages/odbc/versions/1.0.1) and the SQL Server driver. 

```
# Bash 

# Install the unixODBC library
apt-get install unixodbc unixodbc-dev

# SQL Server ODBC Drivers (Free TDS)
apt-get install tdsodbc
```

```
# Within R

# Install the latest odbc release from CRAN:
install.packages("odbc")

```

**Comment by filipsch** [comment]
Cool, i'll look into making it available asap.

**Comment by filipsch** [comment]
@jbarillas a new image is active, that features the ubuntu and R packages that you mentioned. I'll close this issue, but feel free to reopen if anything is not working as you'd expect it to!
