### ISSUE TITLE
Add packages

### ISSUE THREAD

**Issue by aaramirez** [datacamp/datacamp-light#45]
Please add the following packages:

shinydashboard
fPorfolio
timeSeries
pastecs
fMultivar

**Comment by filipsch** [comment]
@aaramirez these are R packages on CRAN, I presume? What versions would you like?

**Comment by aaramirez** [comment]
Hello, the versions i use follows:

"shinydashboard", "0.5.3"
"fPortfolio", "3011.81"
"timeSeries", "3022.101.2"
"pastecs", "1.3-18"
"fMultivar", "3011.78"

Updated versions should work too.

**Comment by filipsch** [comment]
@aaramirez `shinydashboard` is probably not going to be supported out of the box inside DataCamp Light; it's a pretty complex tool.

**Comment by filipsch** [comment]
All packages you list except for `shinydashboard` should be available now!
