### ISSUE TITLE
Package request for plm

### ISSUE THREAD

**Issue by BrianAronson** [datacamp/datacamp-light#47]
Please add the most recent version of the "plm" R package (available on CRAN) to DataCamp. 

It is basically the "go to" tool for conducting regression analyses with time-series data (e.g. fixed effects models). The Journal of Statistical Software article that describes this R program has 400 citations on Google Scholar.

Best,

Brian

**Comment by filipsch** [comment]
@BrianAronson the package should be available now!

**Comment by BrianAronson** [comment]
Thanks!
