### ISSUE TITLE
shiny package generating error

### ISSUE THREAD

**Issue by aaramirez** [datacamp/datacamp-light#48]
I am trying to run a shiny app (very simple) and throws an error.

library(shiny)
ui <- fluidPage()
server <- function(input, output) {}
shinyApp(ui = ui, server = server)

DataCamp encountered the following error during console:
Error in file(file, ifelse(append, "a", "w")): cannot open the connection

Please try again, or refresh the page. Sorry for any inconvenience.
>

**Comment by filipsch** [comment]
@aaramirez, unfortunately, shiny is not supported in DataCamp Light...
