### ISSUE TITLE
recording user submissions

### ISSUE THREAD

**Issue by UCLATALL** [datacamp/datacamp-light#51]
Is there a way to record and access data from user interactions in DCL?

**Comment by filipsch** [comment]
@UCLATALL currently, this is not yet possible, but we're planning on adding a callback whenever somebody hits the Submit Answer button. We are working on a react rewrite of DCL, after which we'll be able to easily add extra features. We'll keep you posted!

**Comment by jimstigler** [comment]
Related to this, is it possible to have separate RUN and SUBMIT buttons in DCL?

**Comment by filipsch** [comment]
Good idea! We'll look into this option during the rewrite as well!

**Comment by jimstigler** [comment]
Hi filipsch, any idea on what the timeline is on the rewrite? The callback is mission critical for my project, and the separate Run and Submit Answer buttons would be really nice.

**Comment by filipsch** [comment]
@jimstigler sorry for the late response. We're currently wrapping up on the rewrite, but still have to do thorough testing. Realistically speaking, getting the app out without enhancements to everybody out there will be for mid December. The first enhancements would be rolling out on a continuous basis around EOY. There is not a detailed roadmap for that, however, but I'll let you know as soon as we do.

**Comment by UCLATALL** [comment]
Hi @filipsch - is there an update on the release date for the rewrite? Will it include the callback to indicate whether the student got the exercise correct or not? Thanks!

**Comment by rv2e** [comment]
Hi, @UCLATALL. The rewrite should be finished soon. Once we have a stable version, we will start doing improvements. Any contributions will be very welcomed as well. We will keep you in touch.

**Comment by jimstigler** [comment]
@filipsch Can you share an update on the rewrite? Is there a way for us to contribute? We are very interested in helping get DCL to the next level.

**Comment by UCLATALL** [comment]
We will start testing immediately! Congratulations on getting this out! We will follow up with feedback.

**Comment by UCLATALL** [comment]
Also, note our suggestion above: would be great to **optionally** have both a RUN and SUBMIT button, so students could test out ideas before "submitting" to the teacher.

**Comment by iamarcel** [comment]
I'll close this issue now, as these suggestions have been merged with #2 and #94.

**Comment by iamarcel** [comment]
@UCLATALL @jimstigler 

These features are now available! You can add a callback when a student starts DataCamp Light, when they submit a solution and when feedback for the exercise is returned (which includes whether the solution was correct). You can also add an option to always show the Run button.

- [Read the details on adding your callbacks.](https://cdn.datacamp.com/dcl-react-prod/index.html#tutorial-customizing-integrating)
- [Read the details on all exercise options.](https://cdn.datacamp.com/dcl-react-prod/index.html#tutorial-customizing-exercise)
