### ISSUE TITLE
Jquery conflict embedding into my application page

### ISSUE THREAD

**Issue by colingoldberg** [datacamp/datacamp-light#54]
Hi,

I tried embedding datacamp-light into my application in these two steps:
- <script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script>
- in a function, called on a button click, I am using jquery to open a dialog box containing the datacamp editor.
ie.
`var template_html = '<div data-datacamp-exercise data-lang="python">'
				+ '<code data-type="pre-exercise-code"></code>'
				+ '<code data-type="sample-code"></code>'
				+ '<code data-type="solution"></code>'
				+ '<code data-type="sct"></code>'
				+ '</div>';
		document.getElementById("editor-dialog").innerHTML = template_html;
	    $("#editor-dialog").dialog({...`

It immediately gets error "Uncaught TypeError: $(...).dialog is not a function" - an apparent conflict with jquery.

Is this a known issue?

Colin Goldberg

**Comment by filipsch** [comment]
@colingoldberg Thanks for flagging it. Do you have this webpage running somewhere online, so we can easily reproduce / research?

**Comment by colingoldberg** [comment]
I have cloned index.html so as to include 'https://cdn.datacamp.com/datacamp-light-latest.min.js' - you can access it by going to:
http://sandbox.ritc.io:1880/datacamp.html

Click on the person icon and click login. It immediately fails and debug shows:
`Uncaught TypeError: $(...).dialog is not a function
    at Object.showRitcLoginPanel (ritc.js:179)
    at Object.onselect (user.js:120)
    at HTMLAnchorElement.<anonymous> (menu.js:99)
    at HTMLAnchorElement.dispatch (jquery-1.11.1.min.js:3)
    at HTMLAnchorElement.r.handle (jquery-1.11.1.min.js:3)`

If you log in using index.html, you will get past this point.
ie.
http://sandbox.ritc.io:1880

Colin Goldberg

**Comment by iamarcel** [comment]
Hi! We've now [rewritten DCL](https://github.com/datacamp/datacamp-light/tree/beta) in a way that is a lot more self-contained. It's in beta right now but feel free to try it out. You shouldn't have this issue anymore!
