### ISSUE TITLE
add rasa_nlu & rasa_core packages to python env

### ISSUE THREAD

**Issue by amn41** [datacamp/datacamp-light#56]
I'd like to try using datacamp-light as part of the documentation for [Rasa NLU](https://github.com/RasaHQ/rasa_nlu) & [Rasa Core](https://github.com/RasaHQ/rasa_core)

**Comment by filipsch** [comment]
@amn41 some quick questions:
- Do the code snippets take long to run, or do they require big data? DataCamp Light chunks will only get 800mb of RAM, and the session times out after 25s.
- Can you provide detailed install instructions for both packages? 
Thanks!

**Comment by iamarcel** [comment]
I'll close this for now due to inactivity. Feel free to reopen if you have something more to help us out!
