### ISSUE TITLE
add console clear button

### ISSUE THREAD

**Issue by Akhi1** [datacamp/datacamp-light#57]
Hi there I think a console clear button somewhere inside the interactive shell will be great. Sometimes a learner/user will play around with trying some random stuff and the previous outputs will get piled up creating a confusion.

**Comment by iamarcel** [comment]
We're keeping issues in the issue tracker for bugs only, now, so I'll close this and [move it to the roadmap](https://github.com/datacamp/datacamp-light/projects/1#card-10364309).

**Comment by ewwink** [comment]
Done? how to add?
