### ISSUE TITLE
ggformula and mosaic for datacamplight 

### ISSUE THREAD

**Issue by maryctucker** [datacamp/datacamp-light#58]
We would like to use ggformula and mosaic with Datacamp Light. Could you add these packages? 

Thank you!

**Comment by filipsch** [comment]
@maryctucker which versions would you like?

**Comment by maryctucker** [comment]
The most recent versions would be great. Thank you!

**Comment by filipsch** [comment]
@maryctucker Okay!  `ggformula v0.6` and `mosaic v1.1.0` are installing, along with dependencies in a new Docker image. This image build can take a while, but it should be up by tomorrow morning Belgian time (in around 10 hours)!

**Comment by maryctucker** [comment]
Awesome! Thanks so much for the quick turn around. We really appreciate it.

**Comment by filipsch** [comment]
The packages should be available now. Enjoy!
