### ISSUE TITLE
quantmod::getSymbols() gives error

### ISSUE THREAD

**Issue by dppalomar** [datacamp/datacamp-light#59]
Hi, I am just trying the package tutorial for the first time to teach a class.
However, I ran into problems right away when I tried to load financial data:
library(quantmod)
getSymbols("^GSPC")
> Error: cannot open URL 'http://ichart.finance.yahoo.com/table.csv?s=^GSPC&a=0&b=01&c=2007&d=10&e=11&f=2017&g=d&q=q&y=0&z=^GSPC&x=.csv'

The same two lines I can execute on my local RStudio. DataCamp quantmod version is only 0.4.7 instead of 0.4.9, but I don't think that's the issue...

Thanks
Daniel

**Comment by filipsch** [comment]
Hi @dppalomar, I will start by upgrading the version, to see if that fixes anything. Will let you know when that's up!

**Comment by filipsch** [comment]
@dppalomar The updated package should now be loaded the next time you try a DataCamp Light chunk. I checked, and for me it works now. Can you confirm and close when your problem is resolved?

**Comment by dppalomar** [comment]
It works, thanks!!
