### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ilkerarslan** [datacamp/datacamp-light#60]
Hi, 

I am using "Datacamp Light" plugin for my education site which is in Turkish. Is it possible to translate button labels "Hint", "Run", "Solution" and the sentence "Powered by Datacamp" to Turkish language? 

I am using Loco plugin to translate other plugins but that didn't work for Datacamp Light.

**Comment by filipsch** [comment]
Hi @ilkerarslan, unfortunately it is not possible to change the text of the different buttons in the DataCamp Light interface. It's a great suggestion though, that would help with embedding this in non-English material. We're currently working on a react rewrite of the app, and we'll consider it when doing the next round of enhancements after launching that. Thanks!

**Comment by iamarcel** [comment]
We're keeping issues in the issue tracker for bugs only, now, so I'll close this and [move it to the roadmap](https://github.com/datacamp/datacamp-light/projects/1#card-10357762).

**Comment by YuandongQi** [comment]
Hi,
I try to add comments in Chinese (for example: 测试) within the r code chunk as I normally do in the static R markdown, but it doesn't work at all in the interactive setting (nothing displayed properly), any ideas?
