### ISSUE TITLE
Add package

### ISSUE THREAD

**Issue by Tellechea19** [datacamp/datacamp-light#61]
Please add the following packages:

- tvm
- lpSolve
- linprog

**Comment by filipsch** [comment]
@Tellechea19 Are these R packages? Which versions would you prefer? Thanks.

**Comment by Tellechea19** [comment]
Yes, they are R packages.

- tvm 0.3.0
- lpSolve 5.6.13
- linprog 0.9-2

Thank you

**Comment by filipsch** [comment]
@Tellechea19 should be up!
