### ISSUE TITLE
Exercise at "en/Loops" forces for a specific variable name

### ISSUE THREAD

**Issue by manikantants** [datacamp/datacamp-light#62]
Exercise at "http://www.learnpython.org/en/Loops" forces for a specific variable name "number" for loop iteration. Giving any other variable name doesn't work

**Comment by filipsch** [comment]
@manikantants the submission correctness test that is written for the DataCamp Light chunk decides how strict the checking happens. You can contact the authors of Learn Python to make it more robust as this is a content issue, not a product issue. Thanks!
