### ISSUE TITLE
Is there a way to specify the height of the window for a DataCamp Light exercise?

### ISSUE THREAD

**Issue by jimstigler** [datacamp/datacamp-light#63]
It would be good to be able to leave more room for exercises that require more code.

**Comment by jimstigler** [comment]
In the documentation it says there is a setting data-height, but I can't get it to do anything. For example: <div data-datacamp-exercise data-height="800px" data-lang="r"> doesn't change the height from the default. Maybe I'm using it wrong?

**Comment by filipsch** [comment]
@jimstigler I don't see the example you posted; could you update your comment?

**Comment by jimstigler** [comment]
Sorry - here is what I tried:
<div data-datacamp-exercise data-height="800px" data-lang="r">

**Comment by EvertEt** [comment]
You should specify the height as a number, omitting the `px` as seen in this example:
https://github.com/datacamp/datacamp-light/blob/master/example/example-r.html#L15
