### ISSUE TITLE
Allow SQL as a language

### ISSUE THREAD

**Issue by Kacawi** [datacamp/datacamp-light#64]
Not an urgent request at all, but was thinking it would be maybe nice to have this also for SQL - It's a nice to have for the Community. @filipsch what do you think?

**Comment by filipsch** [comment]
@Kacawi good idea. We're thinking about supporting both SQL and Shell. The new version of DataCamp light, which will be a rewrite in React, should deploy soon. After that, there will be a discussion about which enhancements and features to work on next (if there is bandwidth). We'll keep you posted.

**Comment by Kacawi** [comment]
Alright, thank you very much, @filipsch! :)

**Comment by galexy** [comment]
Cool! When is the react rewrite expected?

**Comment by filipsch** [comment]
@galexy should be deployed next Wednesday if all goes well.

**Comment by iamarcel** [comment]
We're keeping issues in the issue tracker for bugs only, now, so I'll close this and [move it to the roadmap](https://github.com/datacamp/datacamp-light/projects/1#card-10364361).

**Comment by Schantanu** [comment]
Thank you for working on this. I have already found Datacamp light as a great solution for quick interactive learning without much of backend setup compared to others. My users are eagerly awaiting this so will be great to know any updates.

**Comment by rv2e** [comment]
Hi, thanks for using DatacampLight. We are halfway of supporting SQL (related [commit](https://github.com/datacamp/datacamp-light/commit/041cc7425fefee5cb4adf09069997de50f8d5169)). Unfortunately, we don't have that much time currently so we have to postpone the release to a bit later.
