### ISSUE TITLE
Package install request 

### ISSUE THREAD

**Issue by UCLATALL** [datacamp/datacamp-light#66]
Hello, 

Could you please install the following packages? 
Lock5withR
Lock5Data

Thank you very much for your help.

**Comment by filipsch** [comment]
@UCLATALL i've triggered a new build of the R image that is used to spin up sessions on DataCamp light, that includes the installs for the two packages you mentioned. If the build passes, I will activate this new image around 10am BE time tomorrow (Tuesday). Will keep you posted!

**Comment by filipsch** [comment]
Should be up now!
