### ISSUE TITLE
Adding a R package - iNZightPlots

### ISSUE THREAD

**Issue by annafergusson** [datacamp/datacamp-light#67]
Is there anyway you could add the iNZightPlots package? 

It can be installed from this repository: http://r.docker.stat.auckland.ac.nz/R/
or from github: https://github.com/iNZightVIT/iNZightPlots

**Comment by filipsch** [comment]
Hi @annafergusson would you mind providing exact install instructions, so we can translate those easily to the specification of the Docker image? Thanks.

**Comment by filipsch** [comment]
@annafergusson that should work! Can you also list out what all the dependencies for this package are, and which versions you would need for these dependencies? I want to make sure we have full control over which versions we add. By what time do you need this?

**Comment by annafergusson** [comment]
The dependencies are: grDevices, stats, utils, grid, boot, s20x, survey, quantreg, hexbin, hextri, colorspace, dichromat, iNZightMR

Sorry, I don't know what versions are needed for these dependencies. 

There's no urgency to this request :-)

**Comment by filipsch** [comment]
@annafergusson The build is running, i'll check tomorrow if it passed, and activate the image if it passed. If this is done, your packages will be available.

**Comment by annafergusson** [comment]
Thank you so much @filipsch

**Comment by filipsch** [comment]
should be up!
