### ISSUE TITLE
import pyspark ERROR

### ISSUE THREAD

**Issue by AIITech** [datacamp/datacamp-light#69]
Hello datacamp-light team,

I try to import pyspark package but I get an error (No module named 'pyspark') 

Could you add this library please to your plugin because it is one of the most important libraries in python?

And thank you for this great plugin.

**Comment by filipsch** [comment]
Hi @AIITech, unfortunately, DataCamp Light does not give you enough RAM memory per session to comfortably run Spark. This is something we might consider in the future, but running spark is currently out of the question. I hope you understand that providing all of these computation resources is a costly affair for DataCamp, and not something we can guarantee for all use-cases.
