### ISSUE TITLE
Add AER package to R environment

### ISSUE THREAD

**Issue by tgudenkauf** [datacamp/datacamp-light#70]

**Comment by filipsch** [comment]
@tgudenkauf which version would you like? :)

**Comment by tgudenkauf** [comment]
Version 1.2-5 would be great! Thank you!

**Comment by filipsch** [comment]
@tgudenkauf A new docker image is building, that contains the `AER` package. If it built successfully, I will probably activate it Tuesday Feb 27, around 9:00am UTC.

**Comment by filipsch** [comment]
Should be up!

**Comment by tgudenkauf** [comment]
It is working perfectly! Thank you so much!
