### ISSUE TITLE
I would like to use the R package "aplpack" in the web servers of datacamp-light.

### ISSUE THREAD

**Issue by filipsch** [datacamp/datacamp-light#73]
@vigonfer commented on [Thu Mar 01 2018](https://github.com/datacamp/datacamp/issues/7)

**Comment by filipsch** [comment]
@vigonfer A new docker image is building, that contains the `aplpack` package (version 1.3.0). If it built successfully, I will probably activate it Friday March 2, around 9:00am UTC.

**Comment by filipsch** [comment]
@vigonfer It's up!

**Comment by vigonfer** [comment]
That´s great, thanks!
