### ISSUE TITLE
Not working on mobile on learnpython.org

### ISSUE THREAD

**Issue by westonstearns** [datacamp/datacamp-light#74]
Our partner learnpython.org has reported that the datacamp light on the page is not loading for ios users. 

I am able to use them successfully on ios chrome, but not on safari. The code simply doesn't run but you can tap run with no result. 

Example link and screenshot:
http://learnpython.org/en/Basic_Operators
![image uploaded from ios](https://user-images.githubusercontent.com/18146758/37004765-9047f632-209f-11e8-9176-340438e9c8b6.png)

**Comment by EvertEt** [comment]
Not a fix but a workaround: The first tap just shows the tooltip, but if you tap run twice in succession (second press with tooltip showing), it runs as expected.

**Comment by ManishMethani** [comment]
Yes even if I tap the button twice on iPhone, it's not working.
Works perfectly on Desktop website.

**Comment by iamarcel** [comment]
I don't have an iPhone so I can't test this myself (works fine on Chrome on my Android phone). Can you send a screenshot of how the new update is not working?
