### ISSUE TITLE
vcd package missing

### ISSUE THREAD

**Issue by jeroenclaes** [datacamp/datacamp-light#76]
Dear all,

First off: thanks for making datacamp light available. It is awesome! 

Could you please add the "vcd" package to the list of available packages on the servers?

https://cran.r-project.org/web/packages/vcd/index.html

Thanks a lot!

**Comment by jeroenclaes** [comment]
Thanks Filip! This is perfect.

**Comment by filipsch** [comment]
@jeroenclaes package should be available.

**Comment by jeroenclaes** [comment]
@filipsch Hartelijk bedankt!
