### ISSUE TITLE
keras package missing

### ISSUE THREAD

**Issue by Kacawi** [datacamp/datacamp-light#77]
In the R DataCamp Light chunks, the `keras` package is missing. (cfr. https://www.datacamp.com/community/tutorials/keras-r-deep-learning)
That gives the following error:
![screenshot 2018-03-14 21 25 46](https://user-images.githubusercontent.com/8349123/37429024-63e1ef86-27ce-11e8-80d1-db95f4af0379.png)

**Comment by filipsch** [comment]
@Kacawi A fix is deployed. The Docker image is now rebuilding, which can take quite some time. I'll keep an eye on it, and is soon as it finished, I'll check again if it works properly this time, and activate afterwards. I'll keep you posted.

**Comment by Kacawi** [comment]
@filipsch Thanks for taking this up so quickly!

**Comment by filipsch** [comment]
@Kacawi package should be available again!

**Comment by markusloecher** [comment]
It seems that the package _gamair_ is missing ?I It would be great if the package or at least the dataset "mpg" could be added to the docker.
Thanks!
Markus
