### ISSUE TITLE
Run line or set of lines

### ISSUE THREAD

**Issue by willgearty** [datacamp/datacamp-light#79]
It would be great to be able to only run a particular line or lines, rather than running the entire script every time.

**Comment by filipsch** [comment]
@willgearty great suggestion! After the rewrite, several shortcuts (such as Cmd + Enter to execute a line) should become available out of the box. If they don't, we'll make sure to add it to the list of enhancements. Thanks.

**Comment by willgearty** [comment]
Any idea when the rewrite will launch? No rush, just excited!

**Comment by filipsch** [comment]
@willgearty it's approaching completion, but hard to put a date to it. We will let you know as soon it deploys.

**Comment by iamarcel** [comment]
We're keeping issues in the issue tracker for bugs only, now, so I'll close this and [move it to the roadmap](https://github.com/datacamp/datacamp-light/projects/1#card-10362739).

In any case, the rewrite is in beta right now! You can check it out here: https://github.com/datacamp/datacamp-light/tree/beta
