### ISSUE TITLE
set.seed() in pre-exercise code is not transferring in sample code

### ISSUE THREAD

**Issue by UCLATALL** [datacamp/datacamp-light#81]
Good afternoon, 

I would like to set a random number generator in the pre-exercise code so that when students generate random numbers in the sample code area, they produce the same output. I have tried including set.seed() in the pre-exercise code, but this does not seem to apply to the sample code area.    
For example: 
Pre-exercise code:            
                require(mosaic)
                require(ggformula)
                require(supernova)
                supernova::Fingers
                set.seed(13)
Sample code:
                # run this code
                mean(resample(1:6, 24))

If there is a way to do this without including set.seed() directly in the sample code area, that would be ideal. We would prefer that students did not see it as part of the exercise. 

Thank you so much for your help!

**Comment by ramnathv** [comment]
@UCLATALL Can you elaborate on what happens when you use `set.seed` in the `pre_exercise_code`? If you have a link to the snippet you are using, that would be very useful to help debug this.

**Comment by UCLATALL** [comment]
Sure, here's a link to the code: https://github.com/UCLATALL/intro-stats-modeling/blob/master/data-camp/chapter-9/ch9-5.html

And here's a link to the exercise: https://uclatall.github.io/intro-stats-modeling/data-camp/chapter-9/ch9-5

Thanks for your help!

**Comment by filipsch** [comment]
@UCLATALL this article might be useful to go through: https://github.com/datacamp/testwhat/wiki/Randomness. Let me know if that solves it for you.

**Comment by UCLATALL** [comment]
That helped. Thank you!
