### ISSUE TITLE
Installing infer package

### ISSUE THREAD

**Issue by ismayc** [datacamp/datacamp-light#82]
I'm leading a workshop on Friday, April 13 and would like to experiment with having DataCamp Light in my xaringan slides just in case workshop participants don't have RStudio installed. It would be great if the `infer` package and its dependencies could be installed. It's currently used in two DataCamp courses with two more in development. We plan to send an update to CRAN in a few days, but for the mean time it can be installed via `remotes::install_github("andrewpbray/infer", ref = "develop")`.

**Comment by filipsch** [comment]
@ismayc sorry for the late response, I was OOO. Still relevant to install it?

**Comment by ismayc** [comment]
No rush on this now. I will reach out again later after `infer` is at version 1.0.

**Comment by ismayc** [comment]
`infer` is now stable at version 0.3.1. No rush on installing but it would be helpful.

**Comment by filipsch** [comment]
cc @rv2e

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint. 

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-39
