### ISSUE TITLE
Removing "Powered by Datacamp" + Suggestions

### ISSUE THREAD

**Issue by AIITech** [datacamp/datacamp-light#83]
I use data camp-light WordPress plugin on my website and I add many exercises into my website and there are many "Powered by Datacamp" in the same page and that's not good for UX and not beautiful and most of the students dislike that because that too much.

Can I remove "Powered by Datacamp" from the exercises and keep only one to the bottom of the page or at the beginning of the blog or course as a reference?

I'll be very happy and grateful if you could help me and teach me how to remove some of these "Powered by Datacamp".

Also, I have 3 suggestions:
1- Make the plugin compatible with LMS for students grades
2- Host jupyter notebook labs because that will help many course creators like me 
for free with reference to data camp (like digital marketing campaign) or premium 
3- Support more data science languages and tools like SQL, Spark, and git

Finally, thank you for this creative plugin and I highly appreciate your efforts.

**Comment by iamarcel** [comment]
In the new [beta version](https://github.com/datacamp/datacamp-light/tree/beta), we've made the logo a lot smaller! If you have access to the HTML code, you can just change the script tag to this:

```js
<script type="text/javascript" src="//cdn.datacamp.com/dcl-react.js.gz"></script>
```

The WordPress plugin doesn't use this beta version yet, though.

If you'd like to make multiple suggestions, would you mind creating a separate issue for each of them? Thanks!

I'm closing this issue now, as your main problem should be resolved.

![screenshot from 2018-05-30 16-24-12](https://user-images.githubusercontent.com/1212234/40726491-26f193b2-6426-11e8-9158-42b1778b57eb.png)
