### ISSUE TITLE
Package request: openxlxs

### ISSUE THREAD

**Issue by benbell95** [datacamp/datacamp-light#84]
Hello,

I am using Datacamp light on my website (currently in testing), and was wondering if its possible to add the "openxlxs" package to the setup - its for importing and writing Excel files, and i wanted to do a demonstration of this on my site.

The package can be found here: https://cran.r-project.org/package=openxlsx

Best,
Ben

**Comment by filipsch** [comment]
Hey @benbell95, a new image build is running that installs the package `openxlsx`, version 4.0.17. If the build is successful, I will activate the new image tomorrow morning, which will make the package available in datacamp light.

**Comment by filipsch** [comment]
Should be up!

**Comment by benbell95** [comment]
Awesome, this works great!
