### ISSUE TITLE
sklearn (CategoricalEncoder)

### ISSUE THREAD

**Issue by AIITech** [datacamp/datacamp-light#85]
Hello datacamp-light,
I am trying to import CategoricalEncoder from sklearn but I get this error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    from sklearn.preprocessing import CategoricalEncoder
ImportError: cannot import name 'CategoricalEncoder'

Note: The CategoricalEncoder class has been introduced recently

**Comment by filipsch** [comment]
Hey @AIITech, the current version of `sklearn` that is running on DataCamp Light is `0.18.1`:

![image](https://user-images.githubusercontent.com/5768479/38854481-e38bef22-4220-11e8-9168-8c11a446fdca.png)

This version indeed does not have CategoricalEncoder in it; this feature appears to have been introduced in `v0.20.dev0` (see [here](http://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.CategoricalEncoder.html)). Unfortunately, we cannot install dev versions of very important packages that are being used by other DCL authors across the web. 

I'm closing this issue for now. When you notice that `CategoricalEncoder` is included in a stable version of `sklearn`, please open an issue so we can take care of the package update. Thanks!
