### ISSUE TITLE
R Package install request

### ISSUE THREAD

**Issue by liao961120** [datacamp/datacamp-light#87]
Hello,

Could you please install the R package "googlesheets"?

https://cran.r-project.org/web/packages/googlesheets/index.html

Thank you very much!

**Comment by filipsch** [comment]
Hey @liao961120, thanks for your request. A new image build is running that installs the package googlesheets, version 0.0.2. If the build is successful, I will activate the new image within 48 hours, which will make the package available in datacamp light. As soon as that is done, I will close this issue. Cheers
