### ISSUE TITLE
Inline plots are too big after expanding

### ISSUE THREAD

**Issue by EvertEt** [datacamp/datacamp-light#9]
Plot -> Expand -> Plot again, the last plot will be 450²

**Comment by ddmkr** [comment]
@EvertEt Could you just set the DC_RENDER_DIMS (or something like that) back to the original dimensions?

**Comment by EvertEt** [comment]
Yes that would be the 'hacky' solution. I suppose I can only safely set them back after the plot has returned, but there might have been other plot calls in the mean time so not modifying them at all would be cleaner.  (Also now you can't really be sure if you are receiving a normal resized version or the expanded version)
