### ISSUE TITLE
Install Request: praw

### ISSUE THREAD

**Issue by CloudKing-GrowLearning** [datacamp/datacamp-light#90]
Hello,
Would it be possible to install the PRAW package?

Thank you

**Comment by filipsch** [comment]
@CloudKing-GrowLearning judging from a google search, this is a Python package? What version would you like?

**Comment by CloudKing-GrowLearning** [comment]
Hello,
The latest version would be good (3.6).  Apologies for not linking package site.

Thank you

**Comment by filipsch** [comment]
Hey @CloudKing-GrowLearning, thanks for your request. A new image build is running that installs the package praw, version 5.4.0, for Python 3.5.2. If the build is successful, we will activate the new image within 48 hours, which will make the package available in DataCamp Light. As soon as that is done, we will close this issue. Cheers

**Comment by rv2e** [comment]
The new image has been deployed including the `praw` package.

**Comment by CloudKing-GrowLearning** [comment]
Thanks you very much
