### ISSUE TITLE
Most recent plot should show whenever a plot is produced #beta

### ISSUE THREAD

**Issue by UCLATALL** [datacamp/datacamp-light#93]
#beta In the beta, when a plot is run, it doesn't update the plot window to show the most recent plot. You need to manually press the Next button to see it.

**Comment by iamarcel** [comment]
Thanks!

**Comment by rv2e** [comment]
@iamarcel  I've added to the roadmap 👍 
Thanks a lot @UCLATALL for the feedback!

**Comment by UCLATALL** [comment]
@rv2e @iamarcel I would actually call this a **bug**, as it doesn't perform the way the original DCL does.
