### ISSUE TITLE
Can not import xgboost

### ISSUE THREAD

**Issue by AIITech** [datacamp/datacamp-light#95]
Hello DataCamp-Light team,

I am getting Traceback error when I try to import xgboost in Python.
As you know it is a very important library and I saw you have xgboost course on DataCamp (Extreme Gradient Boosting with XGBoost). 
I hope you to add this package to DataCamp-Light.

Thank you in advance.

**Comment by rv2e** [comment]
@AllTech Good news, the package has been installed successfully! 👍 
Here is a screenshot of a Datacamp light instance that imports the required package:
<img width="486" alt="screenshot 2018-07-18 15 53 48" src="https://user-images.githubusercontent.com/19872276/42886116-115720f0-8aa3-11e8-9e51-de1e686fa276.png">
