### ISSUE TITLE
install packages raster, aqp

### ISSUE THREAD

**Issue by midraed** [datacamp/datacamp-light#96]
Hello!

I'm trying datacamp light with the goal to develop a digital soil mapping course based on our [DSM cookbook](https://fao-gsp.github.io/SOC-Mapping-Cookbook) edited by [FAO of the UN](http://www.fao.org/documents/card/en/c/I8895EN). 

For doing the test I need packages `raster` and `aqp`. Can you install them please? 

o/

GF

**Comment by rv2e** [comment]
@midraed Good news, the package has been installed successfully! 👍
Here is a screenshot of a Datacamp light instance that imports the required package:
![screenshot 2018-07-18 16 41 22](https://user-images.githubusercontent.com/19872276/42888861-6a36325a-8aa9-11e8-8522-c4488bb5fc0c.png)
