### ISSUE TITLE
Install Boltiot library

### ISSUE THREAD

**Issue by sashoeb** [datacamp/datacamp-light#97]
Hi,

I work for an Internet of Things company (BoltIoT) which recently got 484% funded on [Kickstarter](https://www.kickstarter.com/projects/boltiot/bolt). You can visit us at [boltiot.com](boltiot.com) to know more about our product and what we do.
We are planning to use the plugin inside one of our tutorial websites where we teach students about python. 
It would be great if you could install our custom python library called [`boltiot`](https://github.com/Inventrom/bolt-api-python) which contains shortcuts for most of our APIs to control Bolt devices so that it becomes easier for the students to understand about python.

**Comment by filipsch** [comment]
@sashoeb sure; what are the install commands? Is the package on pypi?

**Comment by sashoeb** [comment]
@filipsch yes, the library is hosted on pypi. https://pypi.org/project/boltiot/#description

pip install boltiot works fine

**Comment by sashoeb** [comment]
@filipsch Any update on this? Thanks in advance!

**Comment by rv2e** [comment]
Good news, the package has been installed successfully! 👍 
Here is a screenshot of a Datacamp light instance that imports the required package:
<img width="486" alt="screenshot 2018-07-18 15 53 48" src="https://user-images.githubusercontent.com/19872276/42886116-115720f0-8aa3-11e8-9e51-de1e686fa276.png">
