### ISSUE TITLE
Bug in R Console

### ISSUE THREAD

**Issue by rv2e** [datacamp/datacamp-light#99]
## Problem
When a user writes directly a command in the R console, the same command is dumped automatically a second time. 

Screenshot:

![screenshot 2018-07-18 16 34 11](https://user-images.githubusercontent.com/19872276/42888391-7878ead4-8aa8-11e8-8cf5-b189f419cf3e.png)

**Comment by filipsch** [comment]
@rv2e Could be because `DC_ECHO` is not specified to be `FALSE`. By default, it might be set to TRUE, in which case the code that is being executed is also included in the output payload sent back by RBackend.

**Comment by rv2e** [comment]
After checking the root cause is indeed the `DC_ECHO` flag that is set to `true` instead of `false`. Thanks for the input @filipsch.

**Comment by rv2e** [comment]
@iamarcel Would you like to create a small PR to solve the problem?

**Comment by nunorafaelrocha** [comment]
We'll work on this over the next Sprint. 

The issue was moved to JIRA https://datacamp.atlassian.net/browse/LE-40
